### ISSUE TITLE
Sending messages dont work

### ISSUE THREAD

**Issue by PiecePaperCode** [PiecePaperCode/pyogame2#26]
Traceback (most recent call last):
  File "pyogame2/pyogame2/test.py", line 41, in <module>
    print(empire.send_message(101175, 'hallo'))
  File "pyogame2\pyogame2\__init__.py", line 777, in send_message
    self.chat_token = response['newToken']
KeyError: 'newToken'

token system is refreshed on every page. instead of the landing page.
sendig messages work only if it is the first thing that is called in empire

**Comment by PiecePaperCode** [comment]
🆕v11 ➕ collect_rubble_field()
